### PR TITLE
add include/exclude

### LINKED ISSUE #3: Pull only one file?
We have development assets (jupyter notebooks and development data) in LFS, but we really only need to pull one file for our Github Action to work. Is there a way to pass only one file to your action? If not, would you accept a PR?

### PR DESCRIPTION
**Pull request by nschloe**
Fixes #3.

### CODE REVIEW

**Comment by sam-hoffman** [comment]
Should there also be an include/exclude argument on the `git lfs pull` line?

**Comment by nschloe** [comment]
I don't know. You tell me. :)

**Comment by sam-hoffman** [comment]
From my reading of the LFS docs I think so 🤔 would you mind adding it?

**Comment by nschloe** [comment]
Link to docs?

**Comment by sam-hoffman** [comment]
Would you mind making this change? I'd also be happy to submit my own PR to do it.

**Comment by nschloe** [comment]
Not sure what's missing so sure, do a PR.

**Comment by sam-hoffman** [comment]
Sorry, my bad - looks like the include/exclude I was looking for are already there. Thanks so much for this great action!

**Pull request merged**
