### PR TITLE
Fix: bad deprecation update

### PR DESCRIPTION
**Pull request by maxlapides**
Yeah, this is 100% my fault for misunderstanding subshells...again. Sorry about this everyone!

Here's where I broke it: https://github.com/nschloe/action-cached-lfs-checkout/pull/23

Fixes https://github.com/nschloe/action-cached-lfs-checkout/issues/24

### CODE REVIEW

**Comment by nschloe** [comment]
This needs some comments.

**Comment by maxlapides** [comment]
@nschloe I'm not sure quite what to comment here. I'm doing my best to migrate the original code to handle the deprecation.

**Comment by nschloe** [comment]
I'd like to see some explanations in the code. I.e.: What exactly is the while loop doing? What does the regex mean? etc.

**Comment by maxlapides** [comment]
@nschloe Okay, comments are added.

**Pull request merged**
